spring.application.name=ejercicio1
# Habilitar la consola web de H2 para poder ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de la conexión (crea una base de datos llamada testdb)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Le decimos a Hibernate que cree las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
